<?php

namespace Database\Seeders\Content;

final class LaravelCourseContent
{
    public static function forLesson(string $lessonTitle): ?string
    {
        return match ($lessonTitle) {
            'Què és Laravel i com s\'organitza un projecte' => "Laravel és un framework PHP pensat per desenvolupar aplicacions web seguint una estructura clara. En lloc de començar un projecte amb fitxers solts, Laravel ja et dona una base amb carpetes, convencions i eines per treballar de manera ordenada.\n\nLaravel segueix el patró MVC, que separa el projecte en tres grans peces:\n- Model: representa les dades i la relació amb la base de dades.\n- View: mostra la informació a l'usuari.\n- Controller: rep la petició, coordina la lògica i prepara la resposta.\n\nQuan crees un projecte nou, hi ha unes quantes carpetes que has de saber identificar des del primer dia:\n- `app/`: conté la lògica principal del projecte. Aquí trobaràs models, controladors, requests i altres classes pròpies.\n- `routes/`: defineix les rutes de l'aplicació. La majoria de pantalles web passen per `routes/web.php`.\n- `resources/views/`: conté les vistes Blade, és a dir, les plantilles HTML que veu l'usuari.\n- `database/`: agrupa migracions, seeders i factories.\n- `public/`: és la carpeta pública. El servidor web apunta aquí i hi viu `index.php`, que és el punt d'entrada.\n- `config/`: guarda fitxers de configuració del sistema.\n\nUna petició típica segueix aquest recorregut: l'usuari entra a una URL, Laravel busca la ruta corresponent, crida un controlador, el controlador recupera dades si cal i finalment retorna una vista.\n\nSi entens aquesta estructura, ja pots començar a moure't per un projecte Laravel real sense tocar coses a cegues.",
            'Rutes web i primer recorregut d\'una petició' => "Les rutes indiquen quina acció ha de fer Laravel quan arriba una petició. Una ruta combina com a mínim tres coses: mètode HTTP, URL i resposta.\n\nExemple:\nRoute::get('/courses', [CourseController::class, 'index'])->name('courses.index');\n\nAquesta línia vol dir:\n- `get`: la petició és de lectura.\n- `/courses`: és la URL que escriu l'usuari.\n- `[CourseController::class, 'index']`: Laravel executarà el mètode `index` d'aquest controlador.\n- `name('courses.index')`: dona un nom intern a la ruta per poder-la reutilitzar.\n\nQuan un usuari entra a `/courses`, el recorregut és aquest:\n1. El navegador envia una petició HTTP.\n2. Laravel rep la petició a través de `public/index.php`.\n3. El sistema de rutes comprova si existeix una coincidència.\n4. Si la ruta existeix, s'executa el controlador o la closure associada.\n5. Laravel genera la resposta i la retorna al navegador.\n\nTambé és important distingir rutes públiques i rutes protegides. Una ruta pública la pot veure qualsevol usuari. Una ruta protegida requereix autenticació o permisos. Això es controla habitualment amb middlewares com `auth`.\n\nTreballar bé les rutes és bàsic perquè són el mapa d'entrada de tota l'aplicació.",
            'Controladors i separació de responsabilitats' => "Una ruta pot fer feina directament, però quan el projecte creix és millor delegar-la a un controlador. El controlador és la classe que rep la petició, decideix què cal fer i retorna la resposta adequada.\n\nExemple:\nclass CourseController extends Controller\n{\n    public function index()\n    {\n        \$courses = Course::latest()->get();\n        return view('courses.index', compact('courses'));\n    }\n}\n\nAquí el mètode `index` fa dues coses importants:\n- consulta els cursos\n- passa el resultat a una vista\n\nEn un CRUD clàssic, un controlador resource sol tenir aquests mètodes:\n- `index()`: llistar registres\n- `create()`: mostrar formulari de creació\n- `store()`: desar un nou registre\n- `show()`: veure un detall\n- `edit()`: mostrar formulari d'edició\n- `update()`: actualitzar dades\n- `destroy()`: eliminar o arxivar\n\nLa idea de fons és la separació de responsabilitats. La ruta no hauria de contenir tota la lògica. La vista tampoc. El controlador coordina, però no hauria d'acabar convertint-se en un bloc gegant. Quan cada peça sap quina feina li toca, el projecte és més fàcil de mantenir.",
            'Migracions i modelatge inicial de dades' => "Les migracions són la manera que té Laravel de descriure la base de dades amb codi. En lloc de crear taules manualment des d'un gestor SQL, escrius fitxers PHP que poden executar-se en qualsevol entorn.\n\nExemple de migració:\nSchema::create('courses', function (Blueprint \$table) {\n    \$table->id();\n    \$table->string('titol');\n    \$table->text('descripcio');\n    \$table->string('nivell');\n    \$table->unsignedInteger('durada_hores');\n    \$table->foreignId('user_id')->constrained()->cascadeOnDelete();\n    \$table->timestamps();\n});\n\nAquest fragment crea una taula `courses` amb:\n- clau primària `id`\n- camps de text com `titol` i `descripcio`\n- un camp `user_id` relacionat amb la taula `users`\n- timestamps automàtics (`created_at` i `updated_at`)\n\nPer crear una migració pots utilitzar una comanda com:\n`php artisan make:migration create_courses_table`\n\nI per executar-les:\n`php artisan migrate`\n\nHas de veure les migracions com l'historial oficial de l'esquema. Si el model de dades canvia, no canvies la base a mà: crees una nova migració. Això permet que qualsevol persona de l'equip pugui reconstruir la base exactament igual.",
            'Vistes Blade i dades compartides amb la interfície' => "Blade és el sistema de plantilles de Laravel. Serveix per generar HTML combinant estructura visual amb dades que arriben del controlador.\n\nUn exemple simple seria:\n<h1>{{ \$course->titol }}</h1>\n<p>{{ \$course->descripcio }}</p>\n\nLes dobles claus `{{ }}` mostren dades escapades. Això és important perquè evita problemes de seguretat com l'execució de codi HTML no desitjat.\n\nBlade també incorpora directives molt útils:\n- `@if`: condicions\n- `@foreach`: recorregut de llistes\n- `@auth`: contingut visible només per usuaris autenticats\n- `@csrf`: protecció dels formularis\n\nUn dels conceptes més útils de Blade és el layout. En lloc de repetir la mateixa capçalera, menú i peu a totes les pàgines, es defineix una plantilla base i després cada vista hi injecta el seu contingut.\n\nA nivell pràctic, Blade et permet construir pantalles llegibles i reutilitzables. La vista ha d'estar orientada a presentar la informació, no a prendre decisions complexes de negoci.",
            default => null,
        };
    }
}
